Repository ArkEcosystem/java-crypto, pull requests merged in 2020-02, with the labels that each got.

#97 fix: Update HTLC claim to support secret of 32 bytes
  src/main/java/org/arkecosystem/crypto/transactions/deserializers/HtlcClaim.java
  src/main/java/org/arkecosystem/crypto/transactions/serializers/HtlcClaim.java
  src/test/resources/transactions/V2/htlc-claim/passphrase.json
  src/test/resources/transactions/V2/htlc-claim/second-passphrase.json
Labels: Complexity: Low, Type: Bugfix

#99 feat: added a task to build standalone jars
  build.gradle
Labels: Complexity: Low, Type: Feature

#101 fix: multipay serde fix and additional tests
  src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
  src/main/java/org/arkecosystem/crypto/transactions/serializers/MultiPayment.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/MultiPaymentTest.java
Labels: Complexity: Low, Type: Bugfix

#103 fix: second signature serde methods and tests
  src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
  src/main/java/org/arkecosystem/crypto/transactions/deserializers/SecondSignatureRegistration.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/SecondSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/TransferTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/SecondSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/TransferTest.java
  src/test/resources/transactions/V2/multi_signature_registration/passphrase.json
  src/test/resources/transactions/V2/second_signature_registration/passphrase.json
Labels: Complexity: Medium, Type: Bugfix

#104 release: sync branches
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Complexity: Low, Type: Release

#108 chore: added github actions release workflow
  .github/workflows/publish-release.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Complexity: Medium, Type: Task

#109 release: 1.0.1
  .github/workflows/publish-release.yml
  build.gradle
Labels: Complexity: Medium, Type: Release

#110 fix: gradle root project naming
  build.gradle
  settings.gradle
Labels: Complexity: Low, Type: Bugfix
