Repository ArkEcosystem/java-crypto, pull requests merged in 2020-01, with the labels that each got.

#85 fix: handle SignatureDecodeException
  build.gradle
  src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
  src/main/java/org/arkecosystem/crypto/utils/Message.java
Labels: Complexity: Low, Type: Bugfix

#81 fix: enable vendorfield for multipayment
  src/main/java/org/arkecosystem/crypto/transactions/builder/MultiPayment.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/MultiPaymentTest.java
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#83 chore: spotless plugin
  build.gradle
  src/main/java/org/arkecosystem/crypto/configuration/Fee.java
  src/main/java/org/arkecosystem/crypto/transactions/builder/AbstractTransactionBuilder.java
  src/main/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistration.java
  src/main/java/org/arkecosystem/crypto/transactions/builder/SecondSignatureRegistration.java
Labels: Bounty: Tier 5, Complexity: Low, Type: Task

#90 chore: add actions for different JDK versions
  .github/workflows/test.yml
Labels: Complexity: Low, Type: Task

#86 chore: merge master into develop
  .github/workflows/test.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
  src/main/java/org/arkecosystem/crypto/utils/Message.java
  src/test/java/org/arkecosystem/crypto/configuration/FeeTest.java
  src/test/java/org/arkecosystem/crypto/configuration/NetworkTest.java
  src/test/java/org/arkecosystem/crypto/identities/AddressTest.java
  src/test/java/org/arkecosystem/crypto/identities/PrivateKeyTest.java
  src/test/java/org/arkecosystem/crypto/identities/PublicKeyTest.java
  src/test/java/org/arkecosystem/crypto/identities/WIFTest.java
  src/test/java/org/arkecosystem/crypto/networks/DevnetTest.java
  src/test/java/org/arkecosystem/crypto/networks/MainnetTest.java
  src/test/java/org/arkecosystem/crypto/networks/TestnetTest.java
  src/test/java/org/arkecosystem/crypto/transactions/FixtureLoader.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/DelegateRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/DelegateResignationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcClaimTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcLockTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcRefundTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/IpfsTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/MultiPaymentTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/SecondSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/TransferTest.java
  src/test/java/org/arkecosystem/crypto/transactions/builder/VoteTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/DelegateRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/DelegateResignationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/HtlcClaimTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/HtlcLockTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/HtlcRefundTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/IpfsTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/MultiPaymentTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/MultiSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/SecondSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/TransferTest.java
  src/test/java/org/arkecosystem/crypto/transactions/deserializers/VoteTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/DelegateRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/DelegateResignationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/HtlcClaimTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/HtlcLockTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/HtlcRefundTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/IpfsTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/MultiPaymentTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/MultiSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/SecondSignatureRegistrationTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/TransferTest.java
  src/test/java/org/arkecosystem/crypto/transactions/serializers/VoteTest.java
  src/test/java/org/arkecosystem/crypto/utils/MessageTest.java
  src/test/java/org/arkecosystem/crypto/utils/SlotTest.java
Labels: Complexity: Low, Type: Task
